### PR TITLE
Fix tests that fails when locale has decimal comma

### PR DESCRIPTION
**Pull request by debbiedub**
The locale is set locally for each failing test.

### CODE REVIEW

**Comment by Bombe** [comment]
Heh, locales. What a bunch of bastards. 😄 

So yeah, this definitely needs to be tackled. However, doing it like this can theoretically cause other tests to randomly break so I’d probably fix that in a different way, i.e. using this thingamajing from JUnit which can wrap tests so that during the test the locale has a fixed value but will be restored to what it was before after the test is finished.

**Comment by Bombe** [comment]
By the way, which locale are you using that `GetStatusAjaxPageTest` fails for you? When I run gradle with “-Duser.language=de -Duser.country=DE” that test does not fail while the other two do…

**Comment by Bombe** [comment]
Hah, sheeit, I was able to get an error by using `zh_TW` and that failed because of some date formatter (because in German January is also abbreviated “Jan,” thereby not failing the test).

**Comment by debbiedub** [comment]
I moved the PR to the next branch instead of the main without reading your comments.

I will investigate if there is a more general way for setting up the environment of the tests.

**Comment by debbiedub** [comment]
This is now changed into a modification of the tests' set-up in build.gradle. Is that the thingamajing you were thinking of?

**Comment by Bombe** [comment]
Heh, no, it wasn’t. 😄 

I fixed this in b3c31725b779d0287fff79728227556751f837f2 and bc8f2705a88d987f597c925fab05b2eb1cf73daa. Thank you for the pull request because even though I didn’t use it it still pushed me to fix the issue. ❤️

**Pull request closed without merging**
